### ISSUE TITLE
扫描速度太慢

### ISSUE THREAD

**Issue by lapsule** [lapsule/ble#2]
- 无论是 Peripherial 还是 Service， 扫描速度都非常慢，不知道什么原因。

**Comment by fuacici** [comment]
用ti sensor tag 试了很多遍, 失败的时候sensor tag 按一下主键才能正常连接|扫描. 用BLE-Utility app 测试也有同样的问题, 扫描速度上系统api的delegate 调用时就及时调用了我写的库的block, 所以这个具体原因我这个库可能搞不定, 我再看看.  (有些时候点进来立马就扫出servce , 是因为设备之间其他app/系统 已经和外设建立连接了, 所以非常快)
