### ISSUE TITLE
模拟设备里面有几个选不了

### ISSUE THREAD

**Issue by lapsule** [lapsule/ble#7]
- 选 Alert Notification Service
- 返回如下图所示结果，是系统受限吗？
  ![1](https://f.cloud.github.com/assets/119215/1555630/26684624-4e6f-11e3-8209-c13d32bdd6a2.jpg)

**Comment by fuacici** [comment]
这个就是昨天下班跟你说的那个问题, ble-utility 虽然能选, 但是实际却扫描不到, 继续查查 , 貌似是系统限制了这个uuid,但是ble-ruility 的用了别的, 但怎么还是搜不到 ...

**Comment by fuacici** [comment]
The specified UUID is not permitted. 说是不允许 换了别的,工具也搜不到, 查也查不到啊
